spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/DATABASE_NAME
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver


logging:
  file: logs/anonapp.log
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG